west:runners:openocd: hack for rcar board
As of now cr7 processor is not initialize using the reset function
but by the custom start_cr7 function.

This may be improved later using a reset catch handler, so that
we don't have to change openocd runner.

Also setting pc register to start symbol on resume doesn't seems
to work, this has to be investigated too.

Last, west debug doesn't connect nicely to openocd on first shot:

Error: GDB missing ack(2) - assumed good
Info : dropped 'gdb' connection
Remote replied unexpectedly to 'vMustReplyEmpty': PacketSize=4000;qXfer:memory-map:read-;qXfer:features:read+;qXfer:threads:read+;QStartNoAckMode+;vContSupported+

Requesting a connection manually
target extended-remote :3334
does connect to openocd.

Signed-off-by: Julien Massot <julien.massot@iot.bzh>